const SET_SINGER = 'SET_SINGER'
const SET_TEST = 'SET_TEST'
const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
const SET_FULL_SCREEN = 'SET_FULL_SRCEEN'
const SET_PLAY_LIST = 'SET_PLAY_LIST'
const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
const SET_MODE = 'SET_MODE'
const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export {
    SET_SINGER,
    SET_TEST,
    SET_PLAYING_STATE,
    SET_FULL_SCREEN,
    SET_PLAY_LIST,
    SET_SEQUENCE_LIST,
    SET_MODE,
    SET_CURRENT_INDEX
}
